### ISSUE TITLE
Problem while generating local container.

### ISSUE THREAD

**Issue by SrSandeepKumar** [electrode-io/electrode-native#360] opened 2017-11-18 11:42 UTC
Not sure whats the problem here but i started getting this error once i run `ern run-android`

```
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.10.1] [Cauldron: -NONE-]

A React Native Packager is already running in a different process
⠇ Generating Container locally[buildAndroidPluginsViews] Something went wrong: TypeError: Cannot read property 'charAt' of undefined
[fillContainerHull] Something went wrong: TypeError: Cannot read property 'charAt' of undefined
[generateContainer] Something went wrong. Aborting Container Generation
✖ Cannot read property 'charAt' of undefined
runLocalContainerGen failed: TypeError: Cannot read property 'charAt' of undefined
An error hapenned : Cannot read property 'charAt' of undefined
```

**Comment by krunalsshah** [comment] 2017-11-20 22:49
@SrSandeepKumar  thanks for reporting the issue. Prior to running this command , we assume you have created the mini-app using `ern create-miniapp <appName>`. We cannot reproduce this issue.
Can you please try the following first? Assuming it's a Mac
Run the following command on a Mac to find the id for the process that is listening on port 8081:
`sudo lsof -i :8081`
Then run the following to terminate the process:
kill -9 <PID>

If above doesn't work - 
* please send the detail steps
* have you updated `package.json` of your mini-app?

**Comment by SrSandeepKumar** [comment] 2017-11-21 05:36
@krunalsshah thanks for the response and steps. Yes app was created using `ern create-miniapp <appName>`.
I ran the commands provided above and it still did not work on running `ern run-android` (can still see the same errors) but `react-native run-android` started serving the app.

**Comment by deepueg** [comment] 2017-11-22 01:04
@SrSandeepKumar please confirm if you are running this on a mac or windows?

**Comment by SrSandeepKumar** [comment] 2017-11-22 10:35
i have been running it in a Mac machine.

**Comment by deepueg** [comment] 2017-11-22 17:52
Thanks. Can you please run the below command and provide us the logs? 
`ERN_LOG_LEVEL=debug ern run-android`

**Comment by belemaire** [comment] 2017-11-22 18:22
@SrSandeepKumar 
We have identified a code path leading to this issue. Not sure this is what you are facing but it's highly probable.
The problem is that one of our supported Android plugin, `react-native-vector-icons`, was missing the necessary plugin hook class in the plugin configuration (stored in the Manifest). We have properly added the require plugin hook class through this commit a few minutes ago https://github.com/electrode-io/electrode-native-manifest/commit/2fa537578661deb9e9b6bab6e5afb290aa7f2d8e).
If your MiniApp has a dependency on `react-native-vector-icons`, this was for sure the issue you were facing. It should be fixed now, so all that you need to do is re-run the `ern run-android` command and it should work. If you are still experiencing the issue, please re-run the command with `debug` log level and paste the log here, we will take a closer look.
Thanks !

**Comment by belemaire** [comment] 2017-12-05 19:15
Closing this one as it does not have any more activity. Reopen if needed.

**Closed by belemaire** 2017-12-05 19:15 UTC
Labels: bug

**Comment by pisalseng** [comment] 2017-12-26 16:26
Hi, everyone I just to use Electrode Native but when I created and run this miniapp got error as below:
 
Generating Container locallyrunLocalContainerGen failed: TypeError: Cannot read property '1' of null
× Cannot read property '1' of null
An error occurred: Cannot read property '1' of null

I developed on Windows 10. What's problems? how to solve it?
Thank you.
