### ISSUE TITLE
Can't create container for an iOS application

### ISSUE THREAD

**Issue by viniciusromani** [electrode-io/electrode-native#881] opened 2018-07-26 19:31 UTC
I am a bit lost on how to create a container to an iOS application. I've tried to create using the combo ```ern create container``` and ```ern publish container``` to constraint it for development. Everything went well until the container integration to my native application phase, I got stuck when trying to run ```carthage update --platform ios``` because of the following error:
<img width="569" alt="screen shot 2018-07-26 at 16 28 22" src="https://user-images.githubusercontent.com/5360777/43284033-ff5c0b00-90f0-11e8-8659-6c2a6a032f24.png">
I've also given a try on creating a cauldron to create and publish the container automatically but it gives me the same error on the same phase again. Am I doing something wrong? 

I am a native iOS developer so I am a bit new on electrode native and even on react-native development, please let me know if you guys need any extra information or file description to help me out :) 

(I've also tried to clean and remove any cache/deliverydata folder and files but I might have done it wrong so, I am still looking for any help)

Here are some screenshots of the Container build:

Debug Scheme:
<img width="791" alt="screen shot 2018-07-26 at 17 13 22" src="https://user-images.githubusercontent.com/5360777/43286059-426323e2-90f7-11e8-8d7b-70c4ca78d5eb.png">

Release Scheme:
<img width="790" alt="screen shot 2018-07-26 at 17 15 47" src="https://user-images.githubusercontent.com/5360777/43286177-9e33792e-90f7-11e8-850d-4676b0fb997a.png">

QADevelopment Scheme:
<img width="792" alt="screen shot 2018-07-26 at 17 17 00" src="https://user-images.githubusercontent.com/5360777/43286217-beaa259a-90f7-11e8-917b-0e4ae67205de.png">
Those are the issues shown on Navigator tab for QADevelopment Scheme:
<img width="265" alt="screen shot 2018-07-26 at 17 18 27" src="https://user-images.githubusercontent.com/5360777/43286299-f331c494-90f7-11e8-8173-e37523cb2dcc.png">

When I tried to generate/publish a container without a cauldron, those errors were also found on Release Scheme that was why I tried to clean build/derived data/cache folders.

Thanks for the quick response @belemaire !

**Comment by belemaire** [comment] 2018-07-26 19:49
Hi @viniciusromani 

Your iOS Container build is obviously failing. Unfortunately  the`xcodebuild` command is usually quite cryptic when it comes to providing meaningful information on what is causing the build failure. 

What can help do diagnose the cause of to the build failure is to open the `ElectrodeContainer.xcodeproj` in XCode and try to build it directly from within XCode.
XCode will report more errors that will help pinpointing the cause of the build failure.

Feel free to update this issue with a screenshot of the errors you get in XCode during the build (from the issues Navigator tab), if you still need some help.

**Comment by viniciusromani** [comment] 2018-07-30 13:04
@belemaire Any idea on how to this it ?

**Comment by viniciusromani** [comment] 2018-08-01 18:57
No problem @belemaire ! 

Unfortunately, I still bring some bad news :( I tried the suggestion from Matheus but I still I get the same errors. I have also noticed some quite weird on my search paths. It looks like there is something wrong with the $(inherited) value. See screenshot below:
<img width="894" alt="screen shot 2018-08-01 at 15 55 36" src="https://user-images.githubusercontent.com/5360777/43542487-841b6f82-95a3-11e8-9c79-8a61ceead341.png">

I am very new on Electrode Native, I might be doing something wrong before this phase. Do you have anything else to recommend me to do?

**Comment by belemaire** [comment] 2018-08-03 18:01
@viniciusromani 

You shouldn't care about `QADeployment` scheme, it is only used for internal Walmart needs, we will remove this build configuration from the public Container soon.

I'm sorry to hear that Matheus suggestion didn't work, nor the other suggestions from other similar tickets.

Unfortunately, as I said we don't really have iOS resources at the moment to deep dive into this build issue that seems to appear only under certain circumstances :( We might allocate an iOS engineer, the week after next.

In the meantime, would be very helpful if we had a way to consistently reproduce the issue. If you have a way to create a minimal iOS native app (can just be a new iOS native app project created from XCode an nothing more) that pulls a minimal Container (with just a miniapp in it for simplicity) from a github repo through Carthage ... and that produce the build issue (at least on your worsktation).
Then you could put both the app the container in two public github repos and I'll give it a try, see if I get the same issue on my workstation.

Can iterate a little bit to pinpoint a bit more the problem (even though we already have some idea of whats causing it but no explanation why it is so), which will help our iOS engineer once he get to dive in this.

**Comment by viniciusromani** [comment] 2018-08-13 15:44
@belemaire 

Thanks for your time man! I've read your answer but I did not have time this past week to get everything done, I plan to do that over this week and I will let you know once I have all repositories set up. Sorry for that and thanks in advance!

**Comment by viniciusromani** [comment] 2018-08-14 19:51
@belemaire 

Hello man, I've made a little document explaining what I want to do and how am I doing that right now. I got stuck on adding MiniApps to the cauldron. Could you help me out?

[Electrode Native.pdf](https://github.com/electrode-io/electrode-native/files/2288287/Electrode.Native.pdf)

**Comment by belemaire** [comment] 2018-08-21 19:47
Closing this one as it is a duplicate of other open issues.
Created a root issue to encapsulate all related issues : #896

**Closed by belemaire** 2018-08-21 19:47 UTC
