### ISSUE TITLE
run-android not working

### ISSUE THREAD

**Issue by Kshitij-Jain** [electrode-io/electrode-native#390] opened 2017-11-28 11:55 UTC
I am trying to run android application in emulator. It is showing ->` An error hapenned : linux is not supported yet`

I am using ern-local-cli : 0.10.1
electrode-native : 1.0.11

**Comment by SrSandeepKumar** [comment] 2017-11-28 15:31
@Kshitij-Jain AFAIK Linux is not supported yet, while its supported in Mac and support for windows is WIP.

**Comment by belemaire** [comment] 2017-11-28 18:48
@Kshitij-Jain Linux is not supported yet indeed for `run-android`. There is not much to do, I have created issue https://github.com/electrode-io/electrode-native/issues/391 to add this support. It'll be shipped in v0.11.0 of Electrode Native, scheduled for December 3.

@SrSandeepKumar Electrode Native is working on Windows (`run-android` as well) since v0.9.0. While most commands are supported on linux, proper support for `run-android` was missing.

**Comment by Kshitij-Jain** [comment] 2017-11-29 07:31
@belemaire I have tried to install ern in windows. It shows no file or directory named ".ern/.ernrc"

**Comment by belemaire** [comment] 2017-12-05 19:14
@Kshitij-Jain : It should work on Windows. I will retry tonight, maybe we introduced a regression in a recent release. If so will open a separate issue.

Closing this one for Linux for now as it is tracked by #391. Will ping back on this thread once #391 is closed.

Thanks for reporting !

**Closed by belemaire** 2017-12-05 19:14 UTC
Labels: Linux
