### ISSUE TITLE
MiniApp Typescript Support?

### ISSUE THREAD

**Issue by gmusick** [electrode-io/electrode-native#770] opened 2018-05-23 00:12 UTC
I'm trying to use typescript to create a MiniApp and am getting the following when running `ern run-android`:

```
✔ Starting React Native packager
⠧ Generating Container[bundleMiniApps] Something went wrong: Error: Command failed: /Users/greg/.ern/versions/0.18.2/node_modules/ern-core/node_modules/.bin/react-native bundle --entry-file=index.android.js --dev=false --platform=android --bundle-output=/Users/greg/.ern/containergen/out/android/lib/src/main/assets/index.android.bundle --assets-dest=/Users/greg/.ern/containergen/out/android/lib/src/main/res

Unable to resolve module `./App` from `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/index.android.js`: The module `./App` could not be found from `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/index.android.js`. Indeed, none of these files exist:

  * `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/App(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/App/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`


[generateContainer] Something went wrong. Aborting Container Generation
✖ Command failed: /Users/greg/.ern/versions/0.18.2/node_modules/ern-core/node_modules/.bin/react-native bundle --entry-file=index.android.js --dev=false --platform=android --bundle-output=/Users/greg/.ern/containergen/out/android/lib/src/main/assets/index.android.bundle --assets-dest=/Users/greg/.ern/containergen/out/android/lib/src/main/res

Unable to resolve module `./App` from `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/index.android.js`: The module `./App` could not be found from `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/index.android.js`. Indeed, none of these files exist:

  * `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/App(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/App/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`


runLocalContainerGen failed: Error: Command failed: /Users/greg/.ern/versions/0.18.2/node_modules/ern-core/node_modules/.bin/react-native bundle --entry-file=index.android.js --dev=false --platform=android --bundle-output=/Users/greg/.ern/containergen/out/android/lib/src/main/assets/index.android.bundle --assets-dest=/Users/greg/.ern/containergen/out/android/lib/src/main/res

Unable to resolve module `./App` from `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/index.android.js`: The module `./App` could not be found from `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/index.android.js`. Indeed, none of these files exist:

  * `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/App(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/App/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`


An error occurred: Command failed: /Users/greg/.ern/versions/0.18.2/node_modules/ern-core/node_modules/.bin/react-native bundle --entry-file=index.android.js --dev=false --platform=android --bundle-output=/Users/greg/.ern/containergen/out/android/lib/src/main/assets/index.android.bundle --assets-dest=/Users/greg/.ern/containergen/out/android/lib/src/main/res

Unable to resolve module `./App` from `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/index.android.js`: The module `./App` could not be found from `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/index.android.js`. Indeed, none of these files exist:

  * `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/App(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/private/var/folders/1c/m9p72__929d5krj03_p9jkk40000gn/T/tmp-41925fpDeN0iUAuL7/node_modules/native-test-miniapp/App/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
```

Steps:

1. `ern create-mini-app NativeTestMiniApp`
2. `ern add --dev typescript`
3. `ern add --dev react-native-typescript-transformer`
4. `tsc --init --pretty -jsx react`
5. Add an `rn-cli.config.js` file that uses the `react-native-typescript-transformer`
6. Rename `App.js` to `App.tsx`
7. `ern run-android` (or `run-ios`)

Ideas?

Thanks.

**Comment by belemaire** [comment] 2018-05-23 17:03
Hi @gmusick 

Unfortunately Electrode Native doesn't support custom transformers (or custom rn-cli.config.js for that matter) for MiniApps yet. The problem is due to the fact that when a Container is created, all MiniApps kind of become one (given that we create a single bundle out of them), even if there is just one of them. Meaning that the entry point for the bundling is an `index.js` file that import all MiniApps, and therefore the bundler only account for this top level 'composite'. This is one of the drawbacks of this approach. Not going into too many details, basically the rn-cli.config.js should be at this top level, and would apply to all MiniApps. We're looking into better isolating the MiniApps so that they can fully use their own transformers, babelrc etc ... but we don't have implemented any solution yet, might have something soon hopefully but no ETA.

I will keep this issue open as it does not have a resolution yet, but is planned to be resolved at some point. Also so that other people facing the same issue can find this issue easily for reference.

**Comment by belemaire** [comment] 2018-08-21 19:56
Moving this one to our backlog

**Closed by belemaire** 2018-08-21 19:56 UTC
Labels: backlog
