### ISSUE TITLE
package com.ern.api.impl.navigation does not exist

### ISSUE THREAD

**Issue by provmichaelsteinberg** [electrode-io/electrode-native#1732] opened 2020-09-19 07:11 UTC
platform version 44
os mac 10.15
java version: openjdk11

running `ern run-android` for my  miniapp to generate the android runner, it is failing to build.  i get the following error
```
✖ /FormMiniApp/android/app/src/main/java/com/walmartlabs/ern/formminiapp/MainActivity.java:5: error: package com.ern.api.i
mpl.navigation does not exist
✖ import com.ern.api.impl.navigation.ElectrodeBaseActivity;
✖                                   ^
✖ /FormMiniApp/android/app/src/main/java/com/walmartlabs/ern/formminiapp/MainActivity.java:11: error: cannot find symbol
✖ public class MainActivity extends ElectrodeBaseActivity {
✖                                   ^
✖   symbol: class ElectrodeBaseActivity
✖ /FormMiniApp/android/app/src/main/java/com/walmartlabs/ern/formminiapp/MainApplication.java:13: error: method initialize
 in class ElectrodeReactContainer cannot be applied to given types;
✖         ElectrodeReactContainer.initialize(
✖                                ^
✖   required: Application,com.walmartlabs.ern.container.ElectrodeReactContainer.Config,com.walmartlabs.ern.container.plugins.CodePushPlugin.Config
✖   found: MainApplication,com.walmartlabs.ern.container.ElectrodeReactContainer.Config
✖   reason: actual and formal argument lists differ in length
✖ /FormMiniApp/android/app/src/main/java/com/walmartlabs/ern/formminiapp/MainActivity.java:13: error: method does not over
ride or implement a method from a supertype
✖     @Override
✖     ^
✖ /FormMiniApp/android/app/src/main/java/com/walmartlabs/ern/formminiapp/MainActivity.java:18: error: method does not over
ride or implement a method from a supertype
✖     @Override
✖     ^
✖ /FormMiniApp/android/app/src/main/java/com/walmartlabs/ern/formminiapp/MainActivity.java:23: error: method does not over
ride or implement a method from a supertype
✖     @Override
✖     ^
✖ 6 errors
✖
✖ FAILURE: Build failed with an exception.
✖
✖ * What went wrong:
✖ Execution failed for task ':app:compileDebugJavaWithJavac'.
✖ > Compilation failed; see the compiler error output for details.
✖
✖ * Try:
✖ Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
✖
✖ * Get more help at https://help.gradle.org
✖
✖ BUILD FAILED in 31s
```

**Comment by friederbluemle** [comment] 2020-09-19 19:48
Hi @provmichaelsteinberg - Is this a newly created miniapp?
Also: To build Android apks, can you try to use JDK8 (it ships with Android Studio)? Android does not fully support Java 11.

**Comment by provmichaelsteinberg** [comment] 2020-09-19 22:37
@friederbluemle this is indeed a new miniapp.  i will try out jdk 8

**Comment by provmichaelsteinberg** [comment] 2020-09-19 22:46
@friederbluemle i installed `adoptopenjdk8` and set export JAVA_HOME=`/usr/libexec/java_home -v 1.8` in my zshrc file.  i get the same error.

**Comment by friederbluemle** [comment] 2020-09-19 23:46
Hmm I'm not familiar with `adoptopenjdk8` - I don't _think_ it should make a difference, but Android Studio ships with

```
openjdk version "1.8.0_242-release"
OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
```

Can you please post the output of `ern --version` and `node -v`?

**Comment by provmichaelsteinberg** [comment] 2020-09-21 18:02
```
ℹ electrode-native: 1.1.1
ℹ ern platform: 0.44.1
```
node
```
v12.18.4
```

i can remove my `JAVA_HOME` setting i think?

**Comment by provmichaelsteinberg** [comment] 2020-09-21 18:04
```
 /usr/libexec/java_home -V                                                                                <<<
Matching Java Virtual Machines (3):
    13.0.2, x86_64:     "OpenJDK 13.0.2"        /Library/Java/JavaVirtualMachines/openjdk-13.0.2.jdk/Contents/Home
    11.0.8, x86_64:     "AdoptOpenJDK 11"       /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
    1.8.0_265, x86_64:  "AdoptOpenJDK 8"        /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
```

java version i have available

**Comment by friederbluemle** [comment] 2020-09-23 00:28
Unfortunately I'm not able to reproduce this locally.

I think you can't remove `JAVA_HOME` if you have newer versions of Java installed (afaik it will select the latest one by default).

If `java -version` tells you something similar to what I've posted above, it _should_ work. Are you able to run regular Android apps via Android Studio, and how about plain React Native apps?

**Comment by provmichaelsteinberg** [comment] 2020-09-24 20:19
output from `java -version`

```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```


i will try a plain react native app

**Comment by provmichaelsteinberg** [comment] 2020-09-24 20:24
confirmed i can launch a new empty android project

**Comment by choudharyabhinav15** [comment] 2020-10-13 11:01
@friederbluemle - I am also facing the same issue. Let me know if @provmichaelsteinberg find any solution for this please.

**Comment by choudharyabhinav15** [comment] 2020-10-13 11:19
@friederbluemle - Could you please provide the step by step setup guide in order to create electrode-native app? I really need help as we are trying but it is not working. I tried to find the documents but couldn't get. Thank you in advance.

**Comment by choudharyabhinav15** [comment] 2020-10-13 20:46
@deepueg - Thank you. It worked. Now I am trying to generate the .apk. I think using react-native run-android --variant=release. We can generate the apk file. But is there a way to generate to build the js & android code and generate the .apk file. Also what is the use of the Cauldron & Containers? It is very interesting and I would like to learn. If you have any video or step by step process tehn it will be great.

**Comment by deepueg** [comment] 2020-10-14 17:53
@choudharyabhinav15 Please find the electrode native documentation [here](https://native.electrode.io/).

**Comment by deepueg** [comment] 2020-10-14 17:56
Closing this ticket since the above steps seems to resolve the issue. @provmichaelsteinberg Please feel free to reopen if the steps does not work for you.

**Closed by deepueg** 2020-10-14 17:56 UTC
