### ISSUE TITLE
Code Push Release errors out with access key error

### ISSUE THREAD

**Issue by chrisdojo** [electrode-io/electrode-native#546] opened 2018-02-06 20:35 UTC
I am trying to use electrode and code push for OTA updates but when attempting to do a CodePush publication with ern I am getting the following error:

`✖ The session or access key being used is invalid; please run "code-push login" again. If you are on an older version of the CLI, you may need to run "code-push logout" first to clear the session cache.
performCodePushOtaUpdate {e}
An error occurred: The session or access key being used is invalid; please run "code-push login" again. If you are on an older version of the CLI, you may need to run "code-push logout" first to clear the session cache.
`

I've attempted to logout and log back in multiple times but nothing seems to work. I have verified that I am logged in with `code-push whoami` and it successfully returns my information. I can also successfully use other code-push commands directly without ern

**Comment by belemaire** [comment] 2018-02-06 21:54
@chrisdojo 
Could you please let us know which version of the code-push CLI you are running(`code-push -v`), so that we can try to reproduce.

**Comment by chrisdojo** [comment] 2018-02-06 22:01
@belemaire 
Code push version is: 2.1.6

Electrode native: v0.11.3

Thanks for the help

**Comment by belemaire** [comment] 2018-02-06 22:48
I think I know the reason.

Electrode Native is first looking for the access key in the local platform configuration.

If it does not find it here (key is not set), then it defers to looking for the default global code-push CLI config file (`~/.code-push.config`).

The problem here is that if you are doing login/logout using the code-push CLI, it only updates the access key inside the `~/.code-push.config` file managed by code-push CLI. It does not update the key stored in Electrode Native local configuration file.

Rationale for storing key inside Electrode Native configuration file instead of looking for it in the `~/.code-push.config` file was mostly to be able to use Electrode Native on a CI box and allow for doing code-push deployments without having to install the code-push CLI on the machine (but just set the access key in the Electrode Native local config).

We will think about ways to improve this. Maybe it's just the order of precedence that should be reversed. Anyway, for now, to solve your issue, there is two solutions :

- Solution 1

1. `cat ~/.code-push.config`
You will be able to see in this file, the current valid access key. for ex : `{"accessKey":"30e8eacd631c9c406482a6450d32bb0d221ea1c4" ....`

2. Set the access key that you just retrieved in the Electrode Native local configuration. Using the same example :
`ern platform config codePushAccessKey 30e8eacd631c9c406482a6450d32bb0d221ea1c4`

- Solution 2

An alternative solution is just to edit your local Electrode Native configuration file `~/.ern/.ernrc` and remove the  `codePushAccessKey` key/value pair from this configuration file. This way, Electrode Native will not find the key there and will fall back to retrieve the access key from the `~/.code-push.config` file. This is a better solution as you won't have to refresh the code-push access key stored in Electrode Native local configuration file every time you login/logout from code-push.

**Comment by belemaire** [comment] 2018-02-09 22:45
Closing this issue as I am pretty sure what I have described is what you were facing.

Opened https://github.com/electrode-io/electrode-native/issues/558 to avoid similar issues for other users in the future.

Thanks again for reporting.

**Closed by belemaire** 2018-02-09 22:45 UTC
