### ISSUE TITLE
Unsupported plugin. No configuration found in manifest for react-native@0.50.1

### ISSUE THREAD

**Issue by jmatsushita** [electrode-io/electrode-native#317] opened 2017-11-07 12:49 UTC
Hi there,

I'm giving a try at the [Getting Started instructions for electrode-native](https://electrode.gitbooks.io/electrode-native/content/getting-started/getting-started.html) but bumping into an `Unupported plugin` error. 

Please find below the execution log of `ern run-android` which yields this error with the `DEBUG=*`
env variable.

```
~/electrode-native/MovieListMiniApp > DEBUG=* ern run-android
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.10.0] [Cauldron: -NONE-]

A React Native Packager is already running in a different process
⠋ Creating local Container and publishing AAR to maven local  simple-git [ 'remote',
  simple-git   'set-url',
  simple-git   'origin',
  simple-git   'https://github.com/electrode-io/electrode-native-manifest.git' ] +0ms
  simple-git [ 'fetch', 'origin', 'master' ] +22ms
⠦ Generating Container locally  simple-git [ 'reset', '--hard', 'origin/master' ] +536ms
  simple-git [ 'pull', 'origin', 'master' ] +18ms
⠧ Generating Container locally[fillContainerHull] Something went wrong: Error: Unsupported plugin. No configuration found in manifest for react-native@0.50.1
[generateContainer] Something went wrong. Aborting Container Generation
✖ Unsupported plugin. No configuration found in manifest for react-native@0.50.1
runLocalContainerGen failed: Error: Unsupported plugin. No configuration found in manifest for react-native@0.50.1
An error hapenned : Unsupported plugin. No configuration found in manifest for react-native@0.50.1
```

**Comment by belemaire** [comment] 2017-11-07 18:52
@jmatsushita Thanks for reporting this one. It looks like we have a regression in new version 0.10.0 that we just released. We have received similar internal reports.
We are looking into it now.

**Comment by belemaire** [comment] 2017-11-07 19:28
@jmatsushita This has been fixed in #319
Will release patch version `0.10.1` of platform once PR is merged.

**Closed** 2017-11-07 19:29 UTC
Labels: bug

**Comment by belemaire** [comment] 2017-11-07 19:54
@jmatsushita 
Thanks again for reporting :+1:
We have fixed this issue and released a new patch version of platform (`0.10.1`)
You can install/switch to it by running this command :

```console
$ ern platform use 0.10.1
```

Then `ern run android` should properly work.

**Comment by jmatsushita** [comment] 2017-11-10 13:05
It works (apart from the small typo `ern run-android` with the dash). Thanks!

**Comment by SrSandeepKumar** [comment] 2018-01-27 05:50
<img width="1109" alt="screen shot 2018-01-27 at 11 13 33 am" src="https://user-images.githubusercontent.com/9007183/35469094-a809aefa-0353-11e8-99d2-77bc0d76aca2.png">

@belemaire i could see the problem while i run `ern run-android`, it was working fine.
