### ISSUE TITLE
Can't build Ern Runner project with Xcode  

### ISSUE THREAD

**Issue by amloelxer** [electrode-io/electrode-native#226] opened 2017-10-24 13:09 UTC
First of all let me say that I love Electrode-Native and would like to thank you guys so much for building it. I want to integrate it into my companies's existing work flow, but I need to get this sorted out first. 

A common use case of mine is that I frequently build and run on the command line/simulator with `ern run-ios` and everything works fine. It's when trying to build on my phone or simulator from the Xcode Project **after** that I have problems. When trying to build on an actual iPhone/simulator through Xcode (after successfully running `ern run-ios`), I'm met with a bunch of errors specifically from `ElectrodeContainer`. The errors show that I cannot build the ElectrodeContainer because I cannot build the modules `Darwin`, `Foundation`, and `CoreFoundation`, when trying to build the module `UIKit`. I've tried deleting derived data, cleaning the project, and `Parallelize Build` has been unchecked the whole time, but it still hasn't worked. My next step would be to dive into the project settings, but figured I would ask you guys first.  

Relevant Info: Xcode v9.0, Mac OS Sierra v10.12.6, Electrode-Native v0.8.0. iPhone 7 running iOS 11.0 

Steps for me to reproduce
1. Run `ern run-ios` from the command line 
2. Once it's up and running, open the Xcode Runner Project. 
3. Plug in an actual iPhone and press play. 
4. Project won't be able to build because it cannot build/compile the Electrode container.

Attached is a screenshot. Let me know if you have any more questions. Thanks for the help! 

![electrode-native-errors](https://user-images.githubusercontent.com/5010246/31944651-c9a87306-b89a-11e7-88e6-bf4510447b90.png)

**Comment by belemaire** [comment] 2017-10-24 18:07
@amloelxer 
Thanks for the support and your clear bug report.
Some internal users already reported this issue. We're investigating it more deeply to find the root cause, but it seems to be a side effect of the [ios-install-third-party.sh](https://github.com/facebook/react-native/blob/master/scripts/ios-install-third-party.sh) script that is being run during React Native build. 

Some react-native are also facing something similar in some use cases https://github.com/facebook/react-native/issues/15922

One of the temporary work-around we found out was to just remove the `third-party` directory (this is needed only first time and any time after clearing the derived data directory, as the error will resurface again) and to relaunch a build in XCode.

```shell
rm -rf ~/.ern/containergen/out/ios/ElectrodeContainer/Libraries/ReactNative/third-party/
```

If we don't find a nice way to fix the issue at the root, we might add this command in a script that will be executed during iOS runner build.

Please let me know if this solution works for you.

**Comment by belemaire** [comment] 2017-10-24 19:35
So in my case, this workaround does not actually work as such (but I'm using XCode 8 so behavior might differ). I have to do an additional step, which is, while XCode is launched, run `run-ios` command again in a terminal and kill it after it has regenerated the Container (when the simulator list prompt is displayed). Then rebuild in XCode and it works.

This issue is weird and a bit complex, we hope to get resolved soon. Let's keep this issue opened even if the temporary workaround(s) are working, until we get it fixed in platform.

**Comment by amloelxer** [comment] 2017-10-24 22:06
@belemaire weirdly enough removing the third party folder doesn't work at all for me, but running 'ern run-ios', generating the container, killing it, and then building in Xcode works every time (regardless if I remove the third party folder or not). Despite it being a workaround, it works for my needs for now. Thank you for the help!

**Comment by jomnius** [comment] 2018-02-02 11:34
Using platform version 0.12.0 and I'm also seeing similar "failed to build UIKit" error. However not all the time, but occasionally. Here one sample, when compiling generated API swift code from command line:

❌  /Users/jmiettunen/.ern/containergen/out/ios/ElectrodeContainer/Libraries/ReactNative/third-party/boost_1_63_0/boost/compatibility/cpp_c_headers/cstddef:10:1: unknown type name 'namespace'

namespace std {
         ^



❌  /Users/jmiettunen/.ern/containergen/out/ios/ElectrodeContainer/Libraries/ReactNative/third-party/boost_1_63_0/boost/compatibility/cpp_c_headers/cstddef:10:14: expected ';' after top level declarator

namespace std {
         ^



❌  /Users/jmiettunen/.ern/containergen/out/ios/ElectrodeContainer/Libraries/ReactNative/third-party/boost_1_63_0/boost/tr1/tr1/utility:21:20: 'utility' file not found

#     include_next <utility>
                ^



❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKitDefines.h:8:9: could not build module 'Darwin'

#import <Availability.h>
        ^



❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: could not build module 'Darwin'

#include <sys/types.h>
        ^

**Comment by viniciusromani** [comment] 2018-07-24 18:57
Hey all,

Any updates on this? I am getting theses errors when trying to integrate a generated container to an iOS App. When I run ```carthage update --platform iOS``` I got the following:
```
ask failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/viniciusromani/Developer/react-native-test/Carthage/Checkouts/test-container/ElectrodeContainer.xcodeproj -scheme ElectrodeContainer -configuration Release -derivedDataPath /Users/viniciusromani/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/test-container/v1.0.0 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=E724AE85-F78B-49C2-BE83-F079DCE0BAAD -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/viniciusromani/Developer/react-native-test/Carthage/Checkouts/test-container)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/04/m7tct8gx7qb4v4p13_93kypc0000gn/T/carthage-xcodebuild.PZEURy.log
```

I tried to open the generated container project on XCode and run it using Release scheme, that is exactly where those errors raise up. Is there any fix for those on the pipe?

**Comment by belemaire** [comment] 2018-08-21 19:47
Closing this one as it is a duplicate of other open issues.
Created a root issue to encapsulate all related issues : #896

**Closed by belemaire** 2018-08-21 19:47 UTC
