### ISSUE TITLE
How do I specify a Maven local publisher with ERN v0.12.0?

### ISSUE THREAD

**Issue by abdyer** [electrode-io/electrode-native#529] opened 2018-02-01 09:49 UTC
According to the [v0.12.0 release notes](https://github.com/electrode-io/electrode-native/releases/tag/v0.12.0), a publisher configuration is now required in the cauldron. I tried using `file://~/.m2/repository`, but this did not work, nor was any error message displayed.

Also, while there is a command to add a publisher, there are no corresponding commands to update or delete them. This requires subsequent changes to be made manually rather than via the CLI.

Thanks in advance for any clarification you can provide about this.

**Comment by belemaire** [comment] 2018-02-01 17:49
Hi @abdyer 

Unfortunately the path is not correct. The `file` scheme should follow `file:[PATH]`.
So in your case it should be `file:~/.m2/repository`.
Just validated it with a test Cauldron, you can see my config here : https://github.com/belemaire/dev-cauldron/blob/master/cauldron.json#L102
That being said, maven publication should have failed with a clear error message (I can see the error when activating Electrode Native debug log level through `ern platform config logLevel debug` but the error is not properly handled and logged on the info (user) log level).

As for CLI commands, we are thinking of ways to offer commands or a command or a UI or what else to edit Cauldron configuration (Container publishers being one part). We are not there yet, so as of now, most of the configuration stored in the Cauldron should be edited manually in the document itself.

**Comment by abdyer** [comment] 2018-02-01 21:06
Got it. Thanks for the `logLevel` tip, too!

**Comment by abdyer** [comment] 2018-02-02 10:26
@belemaire It looks like I closed this prematurely. I tried the `file:~/.m2/repository` path as well as a Git publisher with the log level set to `trace`, but `ern create-container` ends after logging `[=== Completed mini apps bundling ===]` with no indication of publishing. The local Maven repo and specified Git repo remain empty.

I tried updating the version of a mini-app in the cauldron to force the generation of a new container, but it failed with this error:

```
✖ Cannot read property 'endsWith' of undefined
[addMiniAppToNativeAppInCauldron Cannot read property 'endsWith' of undefined
[performContainerStateUpdateInCauldron] An error occurred: TypeError: Cannot read property 'endsWith' of undefined
An error occurred: Cannot read property 'endsWith' of undefined
TypeError: Cannot read property 'endsWith' of undefined
    at _loop (/Users/USER/.ern/versions/0.12.0/node_modules/ern-core/src/compatibility.js:236:25)
```

If I update the mini-app version and skip the compatibility check with the `-f` option, the container is published to GitHub, but only the files below appear in my local Maven repo:

![screen shot 2018-02-02 at 11 21 10](https://user-images.githubusercontent.com/917981/35728237-402c60e0-080b-11e8-988d-749692c66e63.png)

**Comment by belemaire** [comment] 2018-02-05 17:31
@abdyer 

Sorry to hear this.
Not sure what is going on here :( 
Could you confirm that the two files that get generate in your local maven repo are created by the command run (that they are not left-overs from an old run) by checking the time stamps of those after running the command ?

By they way :  `I tried updating the version of a mini-app in the cauldron to force the generation of a new container`

You don't need to do this anymore. We introduce the `ern cauldron regen-container` a little while back, which allow you to trigger a new container generation without having to change anything in the container itself to trigger regeneration.

**Comment by belemaire** [comment] 2018-02-05 22:57
@abdyer 

We are probably going to release a new patch version 0.12.1 of Electrode Native tomorrow which will include a new command `publish-container` to ease container publication without the need of having to setup anything in a Cauldron.  (https://github.com/electrode-io/electrode-native/pull/539).

We had a few feedbacks already regarding the disappearance of auto local maven publication and we also need a way to publish a container through command line without relying on a Cauldron for our own CI needs.

Will ping back on this issue once we do the release.

**Comment by abdyer** [comment] 2018-02-06 10:23
@belemaire Thanks for reminding me about `ern cauldron regen-container`. For some reason, it's no longer in the docs, so I haven't used it recently. I ran it and can confirm that the two files that appear in my local Maven are from the current command run rather than a previous run.

To rule out any problems with our cauldron, I did the following:
1. Forked `electrode-native-showcaseapp-cauldron` and set it as the active cauldron
1. Ran `ern cauldron upgrade` to support platform version `0.12.0`
1. Added a local Maven publisher config with the file path recommended above to `cauldron.json`
1. Ran `ern create-container`

Unfortunately, the results were the same, which seems to indicate an issue with container generation in v0.12.0.

I hope this helps. Please let me know if there is any additional log info, etc. I can provide. In the meantime, I'll keep an eye out for the v0.12.1 release. Thanks again!

**Comment by belemaire** [comment] 2018-02-06 19:58
@abdyer 
Thanks. I was able to reproduce the issue you're facing where only two files are created.
This is due to the path format :
-  `~/.m2/repository` > Just creates the two files but no artifact
- `/Users/blemair/.m2/repository` > Creates everything properly
We're looking into the root cause and will work on a fix, but in the meantime using a full path will fix the issue.

**Comment by belemaire** [comment] 2018-02-06 20:08
Created issue https://github.com/electrode-io/electrode-native/issues/545 to track this.
Closing this one, feel free to reopen in case using a full path does not solve your problem.

**Closed by belemaire** 2018-02-06 20:08 UTC

**Comment by abdyer** [comment] 2018-02-12 16:25
Unfortunately, upgrading to ERN v0.12.2 did not get the `create-container` command working for me. It still behaves the same way described above.

Luckily, the new `publish-container` command is working with the same relative file `url`:

```
ern publish-container ~/.ern/containergen/out/android/ --version 1.0.0
--publisher maven --url file:~/.m2/repository
--config '{"artifactId":"some-ern-container","groupId":"com.walmartlabs.ern"}'
```
