### ISSUE TITLE
Android runner doesn’t work

### ISSUE THREAD

**Issue by swashcap** [electrode-io/electrode-native#328] opened 2017-11-09 22:16 UTC
Running `ern run-android` in a newly generated project doesn’t work. Steps to reproduce

1. `ern create-miniapp myapp`
2. `cd myapp`
3. `ern run-android`

This produces:

![no-dimension-set](https://user-images.githubusercontent.com/1858316/32632430-72e86c54-c558-11e7-8adf-203de83f79e8.jpg)

```
No dimension set for key window
Function.get
    index.android.bundle?platform=android&dev=true&minify=false:8338:7
Function.get
    index.android.bundle?platform=android&dev=true&minify=false:8260:25
Function.roundToNearestPixel
    index.android.bundle?platform=android&dev=true&minify=false:8275:30
<unknown>
    index.android.bundle?platform=android&dev=true&minify=false:8197:32
loadModuleImplementation
    index.android.bundle?platform=android&dev=true&minify=false:109:5
guardedLoadModule
    index.android.bundle?platform=android&dev=true&minify=false:70:12
_require
    index.android.bundle?platform=android&dev=true&minify=false:54:60
<unknown>
    index.android.bundle?platform=android&dev=true&minify=false:9836:18
loadModuleImplementation
    index.android.bundle?platform=android&dev=true&minify=false:109:5
```

* OS: macOS 10.12.6
* Node.js: 6.12.0
* npm: 3.10.10
* ern platform: 0.9.0
* cauldron: none

**Comment by krunalsshah** [comment] 2017-11-10 22:54
@swashcap 
```
ern create-miniapp myapp
cd myapp
ern run-android
```
```
ern --version

[v0.9.0] [Cauldron: -NONE-]
* ern-local-cli : 0.9.0
* electrode-native : 1.0.9
* npm: '3.10.10'
* node: '6.10.3'
* OS: macOS 10.12.6
```
```
✔ Building and installing application
✔ Launching Android Application
```
Able to launch the `myapp` with 1 emulator [already running] & with no emulator running and starting it when prompted. Can't reproduce the issue.

**Comment by krunalsshah** [comment] 2017-11-17 19:38
@swashcap I am intending to close this issue. If you still encounter this problem please let me know.

**Closed** 2017-11-17 20:06 UTC
Labels: bug, cannot reproduce
