### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by amorettimarcelo** [electrode-io/electrode-native#796] opened 2018-06-06 13:56 UTC
Hey there.
I am following the 'getting started' for iOS project provided by Electrode's team. I was able to run 'ern create-miniapp MovieListMiniApp', edit app.JS and run the app for the first time.
I could also add the MoviesApi, Movies ApiImpl and NavigationApi by running the command 'ern add react-native-ernmovie-api-impl@0.0.11 react-native-ernnavigation-api@0.0.4' and changed all of the files I was supposed to.

after that I tried to run 'ern run-ios' and I got the following errors:

> XCode xcbuild command failed with exit code 65
(node:22642) UnhandledPromiseRejectionWarning: Error: XCode xcbuild command failed with exit code 65

Here is the full stack trace of it:

> MovieListMiniApp $ ern run-ios
>  ___ _        _               _       _  _      _   _
> | __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
> | _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
> |___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
> [v0.19.0] [Cauldron: -NONE-]
> 
> ✔ Starting React Native packager
> ✔ Generating Container
> ✔ Regenerating ios Runner Configuration
> ? Choose an iOS device iPhone X (UDID 9FCE6A32-DD0A-45F8-896D-6BCFE68A8884)
> ✖ XCode xcbuild command failed with exit code 65
> (node:22642) UnhandledPromiseRejectionWarning: Error: XCode xcbuild command failed with exit code 65
>     at ChildProcess.xcodebuildProc.on.code (/Users/.ern/versions/0.19.0/node_modules/ern-local-cli/src/lib/utils.ts:990:13)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at maybeClose (internal/child_process.js:925:16)
>     at Socket.stream.socket.on (internal/child_process.js:346:11)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at Pipe._handle.close [as _onclose] (net.js:557:12)
> (node:22642) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:22642) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

For some reason the app gets installed on the simulator, but when I try to run it, obviously, I get the following screen:
<img width="280" alt="captura de tela 2018-06-06 as 10 55 55" src="https://user-images.githubusercontent.com/39268766/41042512-3a037810-6978-11e8-81d7-37051430ba91.png">

Any suggestion on what should be done to fix it?

**Comment by belemaire** [comment] 2018-06-08 00:15
Hi @amorettimarcelo 

> XCode xcbuild command failed with exit code 65
(node:22642) UnhandledPromiseRejectionWarning: Error: XCode xcbuild command failed with exit code 65

This indicates that the iOS build of the Runner iOS application failed.
In that scenario Electrode Native unfortunately don't log more details so it's hard to pinpoint the precise cause of the issue.
One way to get more info and try to narrow down the problem, is to open the Runner application project (the xcodeproj that is inside the `ios` directory of the MiniApp) in XCode and build it from within XCode.
XCode will give you more detailed errors that helps with figuring out the root cause.
Could you try that and send us screenshots of the errors you get in XCode, then we will be able to further help with this issue.

**Comment by cohen72** [comment] 2018-08-07 13:46
@belemaire Screenshots of the same error I'm experiencing: 

ERN version [v0.22.1]

![image](https://user-images.githubusercontent.com/1394233/43779013-ed68f926-9a5f-11e8-8f4f-0c51df536f22.png)

![image](https://user-images.githubusercontent.com/1394233/43779531-498e5cf4-9a61-11e8-8ccb-a7e11417ce3e.png)

![image](https://user-images.githubusercontent.com/1394233/43779545-51bd1b36-9a61-11e8-8eda-fa0950ef68b1.png)

**Comment by belemaire** [comment] 2018-08-21 19:56
Which version of XCode are you using ?

**Comment by belemaire** [comment] 2018-08-29 01:47
Closing this issue for now. Please reopen if needed.

**Closed by belemaire** 2018-08-29 01:47 UTC
Labels: bug
