### ISSUE TITLE
Unable to "ern run-android" after adding custom api-impl to miniapp

### ISSUE THREAD

**Issue by dharmin007** [electrode-io/electrode-native#704] opened 2018-03-29 05:55 UTC
Hi,

I was able to do `ern run-android` successfully. Then I added a custom api implementation that I generated from a swagger schema to my miniapp using `ern add @company/react-native-api-impl`. Then if I do import in the App.js like this `import NativeApi from "@company/react-native-api-impl";` I get the following error. Any ideas how I can go about figuring out the issue? 

The implementations I generated for the api are for native only, and I want to start the requests from javascript side, just like the NavigationApi.

```
$ ern add @company/react-native-api-impl
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.15.0] [Cauldron: dojo-android-cauldron]

✔ Adding @company/react-native-api-impl@1.0.0 to AndroidSalesPageMiniApp


$ ern run-android
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.15.0] [Cauldron: dojo-android-cauldron]

A React Native Packager is already running in a different process
⠼ Generating Containerreact-native does not have any injection configuration for android platform
⠧ Generating ContainerSkipping react-native as it does not have an Android configuration
⠏ Generating Container[bundleMiniApps] Something went wrong: Error: Command failed: /Users/parth/.ern/versions/0.15.0/node_modules/ern-core/node_modules/.bin/react-native bundle --entry-file=index.android.js --dev=false --platform=android --bundle-output=/Users/parth/.ern/containergen/out/android/lib/src/main/assets/index.android.bundle --assets-dest=/Users/parth/.ern/containergen/out/android/lib/src/main/res

While trying to resolve module `@company/react-native-api-impl` from file `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/android-sales-page-miniapp/App.js`, the package `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js`. Indeed, none of these files exist:

  * `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`


[generateContainer] Something went wrong. Aborting Container Generation
✖ Command failed: /Users/parth/.ern/versions/0.15.0/node_modules/ern-core/node_modules/.bin/react-native bundle --entry-file=index.android.js --dev=false --platform=android --bundle-output=/Users/parth/.ern/containergen/out/android/lib/src/main/assets/index.android.bundle --assets-dest=/Users/parth/.ern/containergen/out/android/lib/src/main/res

While trying to resolve module `@company/react-native-api-impl` from file `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/android-sales-page-miniapp/App.js`, the package `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js`. Indeed, none of these files exist:

  * `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`


runLocalContainerGen failed: Error: Command failed: /Users/parth/.ern/versions/0.15.0/node_modules/ern-core/node_modules/.bin/react-native bundle --entry-file=index.android.js --dev=false --platform=android --bundle-output=/Users/parth/.ern/containergen/out/android/lib/src/main/assets/index.android.bundle --assets-dest=/Users/parth/.ern/containergen/out/android/lib/src/main/res

While trying to resolve module `@company/react-native-api-impl` from file `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/android-sales-page-miniapp/App.js`, the package `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js`. Indeed, none of these files exist:

  * `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`


An error occurred: Command failed: /Users/parth/.ern/versions/0.15.0/node_modules/ern-core/node_modules/.bin/react-native bundle --entry-file=index.android.js --dev=false --platform=android --bundle-output=/Users/parth/.ern/containergen/out/android/lib/src/main/assets/index.android.bundle --assets-dest=/Users/parth/.ern/containergen/out/android/lib/src/main/res

While trying to resolve module `@company/react-native-api-impl` from file `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/android-sales-page-miniapp/App.js`, the package `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js`. Indeed, none of these files exist:

  * `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/private/var/folders/r1/r85x5rjd7zz5mf1frk9h_pg00000gn/T/tmp-4272ErlupAboH77S/node_modules/@company/react-native-api-impl/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
```

**Comment by deepueg** [comment] 2018-03-29 21:16
Hi @dharmin007 
This Looks like an issue with your package itself, as the error says it's not able to find the index.js file.  

Also, just wanted to clarify, you mentioned api impl, did you use `ern create-api` or `ern create-api-impl` command? 
Did you make any manual changes before publishing the API ?

**Comment by dharmin007** [comment] 2018-03-29 22:11
Hi @deepueg 

Thanks for looking into this! I did not make any manual changes yet to the generated api as I wanted to look how it goes before I start making the necessary changes. 

I took the following steps:

1. Created an api from swagger schema using `ern create-api` 
2. Published that to npm
3. Created an api implementation for native only using `ern create-api-impl` comand and provided the name of the npm package that I published in step 2. 
4. I published the generated api-impl to npm. 
5. Added the published api-impl  to miniapp using `ern add`

I wasn't sure whether I should be adding the api or api-impl from npm to the miniapp so I tried adding each of them separately and then both together, but couldn't get it to work. 

Should I use the same npm `--packageName` for both `ern create-api` as well as the `ern create-api-impl`?

**Comment by deepueg** [comment] 2018-03-30 17:58
@dharmin007 Thanks for the details. Which version of the ern platform did you use to create the api impl ? I just found a bug while trying to reproduce your issue which was not allowing me to create an api-impl.

The steps you listed above is correct, you only need to add the `api-impl` package which in turn will add the `api` to the dependencies. I just tried a sample locally here and works fine (After I fixed the bug). 

Is your package published to public npm?

**Comment by dharmin007** [comment] 2018-03-30 20:30
Hi @deepueg, I am using this version:
```
ern-local-cli : 0.15.0
electrode-native : 1.0.14
```

I converted it to a public package: `@classdojo/react-native-api-impl`

**Comment by deepueg** [comment] 2018-03-30 20:51
still can't find the package.!

**Comment by dharmin007** [comment] 2018-03-30 21:55
Oops my bad, forgot to change the dependency as well. Should work now.

**Comment by deepueg** [comment] 2018-03-31 00:48
I have tried adding your api-impl to a sample miniapps and it works fine. Can you please try to add it to another miniapp and see how it behaves?

**Comment by krunalsshah** [comment] 2018-04-27 18:32
@dharmin007 closing the issue. Please reopen if your question is still not addressed.

**Closed by krunalsshah** 2018-04-27 18:32 UTC
