### ISSUE TITLE
ern cauldron update miniapps app descriptor not showing

### ISSUE THREAD

**Issue by clairewli** [electrode-io/electrode-native#418] opened 2017-12-08 18:36 UTC
when run command `ern cauldron update miniapps <app-name>`, platform is not prompted to choose between app descriptor. It shows empty string instead. And when use arrow, then use enter, exception is thrown.

**Comment by belemaire** [comment] 2017-12-08 18:56
Closing this one to open this one (the cause) : https://github.com/electrode-io/electrode-native/issues/419

**Closed by belemaire** 2017-12-08 18:56 UTC
